// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ-Vf2p8dvMAaoIKoV4VU0Q10E8W15Pzc',
    appId: '1:1003471611746:web:c5bba14158108943e8ee3b',
    messagingSenderId: '1003471611746',
    projectId: 'notefuse',
    authDomain: 'notefuse.firebaseapp.com',
    storageBucket: 'notefuse.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf0Ah4-CvDyTEEx40oN_8nW8VpX7jgeCs',
    appId: '1:1003471611746:android:96ae141a6237dd99e8ee3b',
    messagingSenderId: '1003471611746',
    projectId: 'notefuse',
    storageBucket: 'notefuse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKumZaDS_VVpvsPcz2k3uMxyAj-MiWDas',
    appId: '1:1003471611746:ios:994dc62ff9844504e8ee3b',
    messagingSenderId: '1003471611746',
    projectId: 'notefuse',
    storageBucket: 'notefuse.appspot.com',
    iosClientId: '1003471611746-u7e4d8smvugv1b1lraj2216isc5hn9k1.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteFuse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKumZaDS_VVpvsPcz2k3uMxyAj-MiWDas',
    appId: '1:1003471611746:ios:d26f2f778ac6fe74e8ee3b',
    messagingSenderId: '1003471611746',
    projectId: 'notefuse',
    storageBucket: 'notefuse.appspot.com',
    iosClientId: '1003471611746-97h1ogh3va0h9f6op9vl3v8smu07itei.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteFuse.RunnerTests',
  );
}
